# go-installation-playbook.yml
---
- name: Play- golang installation
  hosts: linux
  become: yes
  tasks:
    - name: Delete go binaries" previous installation
      command: rm -rf /usr/local/go
      become: true
    - name: "Create directory for go binaries"
      file:
        path: /usr/local/go/
        state: directory
        owner: root
        group: root
        mode: 0700
    - name: "Download the go into the /tmp directory"
      get_url:
        url: https://go.dev/dl/go1.20.7.linux-amd64.tar.gz
        dest: /tmp/go.tar.gz
        owner: root
        group: root
        mode: 0600
        force: True
    - name: "unarchive go to the directory"
      unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local/go/
        owner: root
        group: root
        mode: 0600
        extra_opts:
          - --strip-components=1
        decrypt: True
        remote_src: True
    - name: "Set permissions for go "
      file:
        path: /usr/local/go/bin/go
        state: file
        owner: root
        group: root
        mode: 0700
    
    - name: "Set permissions for gofmt"
      file:
        path: /usr/local/go/bin/gofmt
        state: file
        owner: root
        group: root
        mode: 0700

    - name: "Add /usr/local/go to the $PATH environment variable"
      lineinfile:
        path: /etc/profile
        line: export PATH="$PATH:/usr/local/go/bin"
        state: present
        create: True
        insertafter: EOF

