version: '2'
services:

  web:
    image: ansible/awx:17.1.0

    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "99:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY"
      - "./conf/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./conf/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "~/.awx/redis_socket:/var/run/redis/:rw"
      - "./projects:/var/lib/awx/projects:rw"
      - "./inventories:/var/lib/awx/inventories:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:17.1.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY"
      - "./conf/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./conf/credentials.py:/etc/tower/conf.d/credentials.py"
      - "~/.awx/redis_socket:/var/run/redis/:rw"
      - "./projects:/var/lib/awx/projects:rw"
      - "./inventories:/var/lib/awx/inventories:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "~/.awx/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    command: postgres -c listen_addresses='*'
    volumes:
      - ~/.awx/pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
